# Lab | Data Cleaning and Formatting

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

# Challenge 1: Data Cleaning and Formatting

## Exercise 1: Cleaning Column Names

To ensure consistency and ease of use, standardize the column names of the dataframe. Start by taking a first look at the dataframe and identifying any column names that need to be modified. Use appropriate naming conventions and make sure that column names are descriptive and informative.

*Hint*:
- *Column names should be in lower case*
- *White spaces in column names should be replaced by `_`*
- *`st` could be replaced for `state`*

In [1]:
# Your code here

In [2]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv')

In [3]:
# Start by taking a first look at the dataframe and identifying any column names that need to be modified

df.columns

Index(['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Policy Type', 'Vehicle Class', 'Total Claim Amount'],
      dtype='str')

In [4]:
# Upper case : ST and GENDER
# Rename ST -> State

In [5]:
# Standardize all column names

df.columns = (
    df.columns
      .str.lower()
      .str.replace(" ", "_")
)

# Rename specific columns
df = df.rename(columns={"st": "state"})

# Check the result
df.columns

Index(['customer', 'state', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'vehicle_class', 'total_claim_amount'],
      dtype='str')

## Exercise 2: Cleaning invalid Values

The dataset contains columns with inconsistent and incorrect values that could affect the accuracy of our analysis. Therefore, we need to clean these columns to ensure that they only contain valid data.

Note that this exercise will focus only on cleaning inconsistent values and will not involve handling null values (NaN or None).

*Hint*:
- *Gender column contains various inconsistent values such as "F", "M", "Femal", "Male", "female", which need to be standardized, for example, to "M" and "F".*
- *State abbreviations be can replaced with its full name, for example "AZ": "Arizona", "Cali": "California", "WA": "Washington"*
- *In education, "Bachelors" could be replaced by "Bachelor"*
- *In Customer Lifetime Value, delete the `%` character*
- *In vehicle class, "Sports Car", "Luxury SUV" and "Luxury Car" could be replaced by "Luxury"*

In [6]:
# Your code here

In [7]:
# Checking Gender column

df["gender"].unique()

<StringArray>
[nan, 'F', 'M', 'Femal', 'Male', 'female']
Length: 6, dtype: str

In [8]:
# Gender column contains various inconsistent values such as "F", "M", "Femal", "Male", "female", which need to be standardized, for example, to "M" and "F".

# Clean inconsistent values
df["gender"] = df["gender"].replace({
    "Femal": "F",
    "female": "F",
    "Female": "F",
    "Male": "M",
    "male": "M"
})

# Convert to uppercase
df["gender"] = df["gender"].str.upper()

# Verify the result
df["gender"].unique()

<StringArray>
[nan, 'F', 'M']
Length: 3, dtype: str

In [10]:
# Inspect current values
df["state"].unique()

<StringArray>
['Washington',    'Arizona',     'Nevada', 'California',     'Oregon',
       'Cali',         'AZ',         'WA',          nan]
Length: 9, dtype: str

In [11]:
# Clean inconsistent values
df["state"] = df["state"].replace({
    "AZ": "Arizona",
    "Cali": "California",
    "WA": "Washington"
})

# Verify the result
df["state"].unique()

<StringArray>
['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', nan]
Length: 6, dtype: str

In [12]:
# Inspect current values
df["education"].unique()

<StringArray>
[              'Master',             'Bachelor', 'High School or Below',
              'College',            'Bachelors',               'Doctor',
                    nan]
Length: 7, dtype: str

In [13]:
# Replace Bachelors to Bachelor

df["education"] = df["education"].replace({
    "Bachelors": "Bachelor"
})

# Verify the result
df["education"].unique()

<StringArray>
['Master', 'Bachelor', 'High School or Below', 'College', 'Doctor', nan]
Length: 6, dtype: str

In [14]:
# Checking In Customer Lifetime Value
df["customer_lifetime_value"].head()

0            NaN
1     697953.59%
2    1288743.17%
3     764586.18%
4     536307.65%
Name: customer_lifetime_value, dtype: str

In [15]:
# Step 1: Remove the % symbol
df["customer_lifetime_value"] = df["customer_lifetime_value"].str.replace("%", "")

# Step 2: Convert to numeric
df["customer_lifetime_value"] = pd.to_numeric(df["customer_lifetime_value"])

# Step 3: Verify the result
df["customer_lifetime_value"].head()
df["customer_lifetime_value"].dtype

dtype('float64')

In [16]:
# Inspect current values
df["vehicle_class"].unique()

<StringArray>
['Four-Door Car',  'Two-Door Car',           'SUV',    'Luxury SUV',
    'Sports Car',    'Luxury Car',             nan]
Length: 7, dtype: str

In [17]:
# replace by Luxury 

df["vehicle_class"] = df["vehicle_class"].replace({
    "Sports Car": "Luxury",
    "Luxury SUV": "Luxury",
    "Luxury Car": "Luxury"
})

# Verify the result
df["vehicle_class"].unique()

<StringArray>
['Four-Door Car', 'Two-Door Car', 'SUV', 'Luxury', nan]
Length: 5, dtype: str

## Exercise 3: Formatting data types

The data types of many columns in the dataset appear to be incorrect. This could impact the accuracy of our analysis. To ensure accurate analysis, we need to correct the data types of these columns. Please update the data types of the columns as appropriate.

It is important to note that this exercise does not involve handling null values (NaN or None).

*Hint*:
- *Customer lifetime value should be numeric*
- *Number of open complaints has an incorrect format. Look at the different values it takes with `unique()` and take the middle value. As an example, 1/5/00 should be 5. Number of open complaints is a string - remember you can use `split()` to deal with it and take the number you need. Finally, since it should be numeric, cast the column to be in its proper type.*

In [ ]:
# Your code here

In [18]:
# Checking Customer lifetime value

df["customer_lifetime_value"].head()

0           NaN
1     697953.59
2    1288743.17
3     764586.18
4     536307.65
Name: customer_lifetime_value, dtype: float64

In [21]:
# Convert all to string
df["customer_lifetime_value"] = df["customer_lifetime_value"].astype(str)

# Remove the % symbol
df["customer_lifetime_value"] = df["customer_lifetime_value"].str.replace("%", "")

# Convert to numeric
df["customer_lifetime_value"] = pd.to_numeric(df["customer_lifetime_value"])

In [22]:
# Verify 
df["customer_lifetime_value"].head()
df["customer_lifetime_value"].dtype

dtype('float64')

In [23]:
# Step 1: Inspect current values
df["number_of_open_complaints"].unique()

# Step 2: Extract middle value from the string
df["number_of_open_complaints"] = (
    df["number_of_open_complaints"]
      .str.split("/")
      .str[1]
)

In [24]:
# Convert to numeric
df["number_of_open_complaints"] = pd.to_numeric(df["number_of_open_complaints"])

# Verify
df["number_of_open_complaints"].head()
df["number_of_open_complaints"].dtype

dtype('float64')

## Exercise 4: Dealing with Null values

Identify any columns with null or missing values. Identify how many null values each column has. You can use the `isnull()` function in pandas to find columns with null values.

Decide on a strategy for handling the null values. There are several options, including:

- Drop the rows or columns with null values
- Fill the null values with a specific value (such as the column mean or median for numerical variables, and mode for categorical variables)
- Fill the null values with the previous or next value in the column
- Fill the null values based on a more complex algorithm or model (note: we haven't covered this yet)

Implement your chosen strategy to handle the null values. You can use the `fillna()` function in pandas to fill null values or `dropna()` function to drop null values.

Verify that your strategy has successfully handled the null values. You can use the `isnull()` function again to check if there are still null values in the dataset.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling null values.

After formatting data types, as a last step, convert all the numeric variables to integers.

In [ ]:
# Your code here

In [25]:
# Identify any columns with null or missing values.

# Count null values in each column
df.isnull().sum()

# Show only columns that contain nulls
df.isnull().sum()[df.isnull().sum() > 0]

customer                     2937
state                        2937
gender                       3054
education                    2937
customer_lifetime_value      2940
income                       2937
monthly_premium_auto         2937
number_of_open_complaints    2937
policy_type                  2937
vehicle_class                2937
total_claim_amount           2937
dtype: int64

In [26]:
# 1: Drop rows with nulls
df_cleaned = df.dropna()

In [27]:
# 2: Fill numerical nulls with mean
df["income"] = df["income"].fillna(df["income"].mean())

# 2: Fill categorical nulls with mode
df["gender"] = df["gender"].fillna(df["gender"].mode()[0])

# Verify
df.isnull().sum()

customer                     2937
state                        2937
gender                          0
education                    2937
customer_lifetime_value      2940
income                          0
monthly_premium_auto         2937
number_of_open_complaints    2937
policy_type                  2937
vehicle_class                2937
total_claim_amount           2937
dtype: int64

In [29]:
# Fill the null values with the previous or next value in the column

# Forward fill
df["income"] = df["income"].ffill()

# Backward fill
df["gender"] = df["gender"].bfill()


df.isnull().sum()

customer                     2937
state                        2937
gender                          0
education                    2937
customer_lifetime_value      2940
income                          0
monthly_premium_auto         2937
number_of_open_complaints    2937
policy_type                  2937
vehicle_class                2937
total_claim_amount           2937
dtype: int64

In [32]:
# After formatting data types, as a last step, convert all the numeric variables to integers.

# 1. Identify numeric columns
numeric_cols = df.select_dtypes(include=["float64", "int64", "object"]).columns

# 2. Convert everything to numeric (invalid values become NaN)
df[numeric_cols] = df[numeric_cols].apply(pd.to_numeric, errors="coerce")

# 3. Fill NaN values
df[numeric_cols] = df[numeric_cols].fillna(0)

# 4. Convert to integer
df[numeric_cols] = df[numeric_cols].astype(int)

/var/folders/t1/g1ptmxln4nx5k_rz9978lf340000gn/T/ipykernel_13513/3975676436.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  numeric_cols = df.select_dtypes(include=["float64", "int64", "object"]).columns

In [34]:
# Verify 
df[numeric_cols].dtypes

customer                     int64
state                        int64
gender                       int64
education                    int64
customer_lifetime_value      int64
income                       int64
monthly_premium_auto         int64
number_of_open_complaints    int64
policy_type                  int64
vehicle_class                int64
total_claim_amount           int64
dtype: object

## Exercise 5: Dealing with duplicates

Use the `.duplicated()` method to identify any duplicate rows in the dataframe.

Decide on a strategy for handling the duplicates. Options include:
- Dropping all duplicate rows
- Keeping only the first occurrence of each duplicated row
- Keeping only the last occurrence of each duplicated row
- Dropping duplicates based on a subset of columns
- Dropping duplicates based on a specific column

Implement your chosen strategy using the `drop_duplicates()` function.

Verify that your strategy has successfully handled the duplicates by checking for duplicates again using `.duplicated()`.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling duplicates.

Save the cleaned dataset to a new CSV file.

*Hint*: *after dropping duplicates, reset the index to ensure consistency*.

In [35]:
# Your code here

In [38]:
# Use the .duplicated() method to identify any duplicate rows in the dataframe.

df.duplicated().sum()

np.int64(2977)

In [37]:
df[df.duplicated()]

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
22,0,0,0,0,2412750,14072,71,0,0,0,511
174,0,0,0,0,578018,51066,74,0,0,0,787
199,0,0,0,0,604702,20396,76,1,0,0,364
255,0,0,0,0,477294,20993,133,0,0,0,638
373,0,0,0,0,3347334,33190,106,0,0,0,508
...,...,...,...,...,...,...,...,...,...,...,...
4003,0,0,0,0,0,39295,0,0,0,0,0
4004,0,0,0,0,0,39295,0,0,0,0,0
4005,0,0,0,0,0,39295,0,0,0,0,0
4006,0,0,0,0,0,39295,0,0,0,0,0
4007,0,0,0,0,0,39295,0,0,0,0,0

In [39]:
# I chose to drop all duplicate rows while keeping the first occurrence.
# This ensures that the dataset contains only unique records and avoids populating the dataset with repeated entries.
# Keeping the first occurrence preserves the original order of the data.

In [40]:
# 1. Drop duplicates (keep first)
df = df.drop_duplicates(keep="first")

# 2. Reset index
df = df.reset_index(drop=True)

In [41]:
# 3. Verify duplicates are gone
df.duplicated().sum()

np.int64(0)

In [42]:
# 4. Save cleaned dataset
df.to_csv("cleaned_dataset.csv", index=False)

# Bonus: Challenge 2: creating functions on a separate `py` file

Put all the data cleaning and formatting steps into functions, and create a main function that performs all the cleaning and formatting.

Write these functions in separate .py file(s). By putting these steps into functions, we can make the code more modular and easier to maintain.

*Hint: autoreload module is a utility module in Python that allows you to automatically reload modules in the current session when changes are made to the source code. This can be useful in situations where you are actively developing code and want to see the effects of changes you make without having to constantly restart the Python interpreter or Jupyter Notebook kernel.*

In [ ]:
# Your code here

# Bonus: Challenge 3: Analyzing Clean and Formated Data

You have been tasked with analyzing the data to identify potential areas for improving customer retention and profitability. Your goal is to identify customers with a high policy claim amount and a low customer lifetime value.

In the Pandas Lab, we only looked at high policy claim amounts because we couldn't look into low customer lifetime values. If we had tried to work with that column, we wouldn't have been able to because customer lifetime value wasn't clean and in its proper format. So after cleaning and formatting the data, let's get some more interesting insights!

Instructions:

- Review the statistics again for total claim amount and customer lifetime value to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount and a low customer lifetime value. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount, and clients with a low customer lifetime value to be those in the bottom 25% of the customer lifetime value. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile and a customer lifetime value in the bottom 25th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount and low customer lifetime value data. To do so, select both columns of the dataframe simultaneously and pass it to the `.describe()` method. This will give you descriptive statistics, such as mean, median, standard deviation, minimum and maximum values for both columns at the same time, allowing you to compare and analyze their characteristics.

In [44]:
# Your code here

In [45]:
# Review the statistics again for total claim amount and customer lifetime value to gain an understanding of the data.
subset_full = df[["total_claim_amount", "customer_lifetime_value"]]
subset_full.describe()

       total_claim_amount  customer_lifetime_value
count         1031.000000             1.031000e+03
mean           404.442289             7.944984e+05
std            294.632567             6.421022e+05
min              0.000000             0.000000e+00
25%            203.000000             4.068095e+05
50%            351.000000             5.913300e+05
75%            532.000000             8.977495e+05
max           2893.000000             5.816655e+06

In [46]:
# Calculate percentiles
claim_75 = df["total_claim_amount"].quantile(0.75)
clv_25 = df["customer_lifetime_value"].quantile(0.25)

# Filter customers
high_claim_low_clv = df[
    (df["total_claim_amount"] > claim_75) &
    (df["customer_lifetime_value"] < clv_25)
]

# Inspect results
high_claim_low_clv.head()
high_claim_low_clv.shape

(39, 11)

In [47]:
# Select both columns
subset = high_claim_low_clv[["total_claim_amount", "customer_lifetime_value"]]

# Get descriptive statistics
subset.describe()

       total_claim_amount  customer_lifetime_value
count           39.000000                39.000000
mean           723.871795            340403.410256
std            151.122672             57172.848405
min            537.000000            228759.000000
25%            632.500000            299438.000000
50%            679.000000            365253.000000
75%            799.000000            386920.500000
max           1185.000000            402381.000000